//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ist420row2Entities : DbContext
    {
        public ist420row2Entities()
            : base("name=ist420row2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<tblMenuItemsDave> tblMenuItemsDaves { get; set; }
        public virtual DbSet<tblMenuItemsGABRIEL> tblMenuItemsGABRIELs { get; set; }
        public virtual DbSet<tblMenuItemsJoey> tblMenuItemsJoeys { get; set; }
        public virtual DbSet<tblMenuItemsTim> tblMenuItemsTims { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
