//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuItemsTim
    {
        public int fldPizzaID { get; set; }
        public string fldPizzaType { get; set; }
        public decimal fldPizzaCost { get; set; }
    }
}
